### PR TITLE
if the vote has ballots the choice cannot be deleted #191

### PR DESCRIPTION
**Pull request by valentinbujdoso**

### CODE REVIEW

**Review by magwas — CHANGES_REQUESTED** [review]
I am not convinced that one condition in the production code warrants 4 testcases.
Do it with one testcase or convince me that all is needed.

**Comment by valentinbujdoso** [comment]
You were right I just copied wrongly one file. :(

**Review by magwas — APPROVED** [review]
nice

**Comment by magwas** [comment]
testcaseCount=1

**Pull request merged**
