### PR TITLE
Compute vote results return contains beats at losers #210

### PR DESCRIPTION
**Pull request by szirbucz**

### CODE REVIEW

**Comment by szirbucz** [comment]
@magwas I see 3 crypto-zombies (n more mutants need to be killed... without details) here. Is it some configuration problem in Sonar or Pitest?

**Comment by magwas** [comment]
As I see the mutation test problems are timeouts. It would be understandable for a fscked recursive code to not terminate. I do not say I understand the problem in its entirety.

**Comment by magwas** [comment]
I would like to ask some time to study the problem. Is it okay if I delay this review to sometimes next week?

**Comment by szirbucz** [comment]
I guess I understand what happens. The unit tests fall in an infinite loop when calculateWinners doesn't return all the choices. It needs a separate unit test for the calculateWinners method.

**Comment by szirbucz** [comment]
I will try it tonight

**Comment by magwas** [comment]
Tell me when it is ready for review or when you need help.

**Comment by szirbucz** [comment]
> Tell me when it is ready for review or when you need help.

I will. I just realized that I wrote test to kill mutants that cause infinite loop, with data preparation that runs infinitely with the same mutants :( (Keep firing a**holes)

**Comment by szirbucz** [comment]
@magwas , ready for review. I could kill the zombies.

**Comment by magwas** [comment]
nice dead zombies you have here
testcasecount=8

**Review by magwas — APPROVED** [review]

**Pull request merged**
